---
title: "Resume"
format: html
---

Ava Madalinski

Fort Collins, Colorado / (971) 288-9866 / [ava.madalinski\@gmail.com](mailto:ava.madalinski@gmail.com) / [LinkedIn](https://www.linkedin.com/in/ava-madalinski-029293349/)\

Motivated Ecosystem Science and Sustainability major with interest in the field of environmental outreach and policy, driven to educate and shape our world for a more sustainable future. In professional settings, I bring a background of sustainability and ecological coursework, with qualities of efficiency and organization. I am eager to apply what I have learned and spread my enthusiasm for the human dimensions of environmental science.  

\

EDUCATION

**B.S. in Ecosystem Science and Sustainability**

**Minor in Spanish May 2027**

Colorado State University, Fort Collins, CO GPA: 4.0

University Honors Student

EXPERIENCE

**Boys and Girls Club, Fort Collins, CO–Youth Development Specialist November 2024-Present**

-   Provide guidance and role modeling to members

-   Maintaining a safe and positive environment for youth

-   Effectively plan and lead programs and activities

-   Communicate constructively with staff and kids

\

**Farmers’ Plate and Pantry, Carlton, OR– Wait Staff/Cashier May 2021-Present**

-   Processed payments of food and drink at the cash register

-   Knowledge of food safety and handling procedures and regulations

-   Prepared and cooked meals and pizzas to order with supervision of chef

-   Handled and resolved customer complaints

-   Waited tables and served customers in an accommodating manner

**Portland Parks and Recreation–Customer Service Representative June 2024-August 2024**

-   Assisted patrons with check-in and other transactions

-   Provided and effectively communicated current information regarding parks and program information to park users

-   Recognized and responded to safety and emergency situations

-   Promoted a welcome and friendly atmosphere

**Grace Art Institute, Portland, OR–Day Camp Counselor June 2022-August 2023**

-   Helped run the on-site glass studio, loading and unloading kilns, glass cutting, demonstrating art projects

-   Led kids 5-13 in games and activities

-   Established meaningful connections with kids and parents

-   Ensured that camp rules were followed and that campers were safe

-   Problem solving and settling disputes between campers

SKILLS

```         
Excel, organization, dependability, flexibility, efficient, interpersonal skills
```

CERTIFICATES

-   Oregon State Seal of Biliteracy in Spanish **Issued 2023**

-   Red Cross CPR and First Aid certified **Issued 2024**

Oregon Food Handlers Card **Issued 2024**
